import { ArchitectureModel, Component, ComponentKind } from "./types.js";

const GROUP_LABEL: Record<ComponentKind, string> = {
  table: "Database",
  endpoint: "API",
  service: "Services",
  dependency: "Dependencies",
  queue: "Messaging",
  job: "Jobs",
};

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function renderMermaid(model: ArchitectureModel): string {
  const byKind = new Map<ComponentKind, Component[]>();
  for (const c of Object.values(model.components)) {
    if (!byKind.has(c.kind)) byKind.set(c.kind, []);
    byKind.get(c.kind)!.push(c);
  }

  const lines: string[] = ["flowchart LR"];

  for (const [kind, comps] of byKind) {
    if (comps.length === 0) continue;
    lines.push(`  subgraph ${sanitizeId(kind)}["${GROUP_LABEL[kind]}"]`);
    for (const c of comps.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`    ${sanitizeId(c.id)}["${c.name}"]`);
    }
    lines.push("  end");
  }

  for (const rel of model.relationships) {
    const label = rel.label ? `|${rel.label}|` : "";
    lines.push(`  ${sanitizeId(rel.from)} -->${label} ${sanitizeId(rel.to)}`);
  }

  return lines.join("\n");
}

export function renderMarkdown(model: ArchitectureModel): string {
  const mermaid = renderMermaid(model);
  const counts = Object.values(model.components).reduce<Record<string, number>>((acc, c) => {
    acc[c.kind] = (acc[c.kind] || 0) + 1;
    return acc;
  }, {});

  const summary = Object.entries(counts)
    .map(([k, v]) => `- ${GROUP_LABEL[k as ComponentKind]}: ${v}`)
    .join("\n");

  return `# Architecture (auto-generated by blug)

_Last updated: ${model.updatedAt}_
_Do not hand-edit — this file is regenerated on every architecture-relevant change._

${summary || "_No components detected yet._"}

\`\`\`mermaid
${mermaid}
\`\`\`
`;
}
