import { type ArchitectureModel, type Component, type ComponentKind } from "./types.js";

const GROUP_LABEL: Record<ComponentKind, string> = {
  table: "Database",
  endpoint: "API",
  service: "Services",
  dependency: "Dependencies",
  queue: "Messaging",
  job: "Jobs",
};

const KIND_ORDER: ComponentKind[] = ["table", "endpoint", "service", "dependency", "queue", "job"];

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function escapeLabel(label: string): string {
  return label
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "/");
}

export function renderMermaid(model: ArchitectureModel): string {
  const byKind = new Map<ComponentKind, Component[]>();
  for (const c of Object.values(model.components)) {
    if (!byKind.has(c.kind)) byKind.set(c.kind, []);
    byKind.get(c.kind)!.push(c);
  }

  const lines: string[] = ["flowchart LR"];

  for (const kind of KIND_ORDER) {
    const comps = byKind.get(kind) ?? [];
    if (comps.length === 0) continue;
    lines.push(`  subgraph ${sanitizeId(kind)}["${GROUP_LABEL[kind]}"]`);
    for (const c of comps.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`    ${sanitizeId(c.id)}["${escapeLabel(c.name)}"]`);
    }
    lines.push("  end");
  }

  const relationships = [...model.relationships].sort((a, b) => {
    const aKey = `${a.from}\0${a.to}\0${a.label ?? ""}`;
    const bKey = `${b.from}\0${b.to}\0${b.label ?? ""}`;
    return aKey.localeCompare(bKey);
  });
  for (const rel of relationships) {
    const label = rel.label ? `|${escapeLabel(rel.label)}|` : "";
    lines.push(`  ${sanitizeId(rel.from)} -->${label} ${sanitizeId(rel.to)}`);
  }

  return lines.join("\n");
}

export function renderMarkdown(model: ArchitectureModel): string {
  const mermaid = renderMermaid(model);
  const counts = Object.values(model.components).reduce<Record<string, number>>((acc, c) => {
    acc[c.kind] = (acc[c.kind] || 0) + 1;
    return acc;
  }, {});

  const summary = KIND_ORDER.filter((kind) => counts[kind])
    .map((kind) => `- ${GROUP_LABEL[kind]}: ${counts[kind]}`)
    .join("\n");

  return `# Architecture (auto-generated by blug)

_Last updated: ${model.updatedAt}_
_Do not hand-edit — this file is regenerated on every architecture-relevant change._

${summary || "_No components detected yet._"}

\`\`\`mermaid
${mermaid}
\`\`\`
`;
}
